### PR TITLE
replace MomentJS 2.29.4 assets with actual files

### PR DESCRIPTION
**Pull request by ashkulz**
This is the same thing that happened in #61 and I fixed via #62 :see_no_evil:

### CODE REVIEW

**Comment by ashkulz** [comment]
@derekprior would appreciate your merging this and releasing 2.29.4.1 to RubyGems :+1:

**Review by muruvetri — APPROVED** [review]
it will nice to have this check on unit-tests when I copied assests it didn't have UMD on my assests, That explains the reason for this issue.

**Comment by derekprior** [comment]
Pushed new release.

**Comment by ashkulz** [comment]
Thanks, @derekprior!

**Pull request merged**
