### PR TITLE
Shortcut for including all locales

### PR DESCRIPTION
**Pull request by Nerian**
Add a shortcut for including all locales.

### CODE REVIEW

**Comment by derekprior** [comment]
Thats a lot of locales. I'm having a hard time envisioning a scenario where you'd want to do this? I would think you'd only include locales you support with translations for the rest of your site, right?

**Comment by Nerian** [comment]
People who want to fine-tune their selection can manually add locales one by one, as it is now. But those who want to support a large number of locales can simply use that one liner. I personally don't mind including all locales that a gem supports instead of adding ~10 locale lines per gem. 

It's just for simplicity's sake.

**Comment by derekprior** [comment]
minimized and gzipped all momentjs locales add 40K to the response. That's not awful, but it's also unnecessary. I don't really want to encourage that, but I supposed that's up to you.

**Comment by Nerian** [comment]
Yes, I understand that adding all locales when you don't need all of them is increasing the size of the response. I think it's okay in my case. I use Turbolinks, so the assets(js and css) are only downloaded once and then the body gets updated via javascript for each request. Also using cache fingerprinting so assets that haven't changed are only downloaded once.

Those two simple things really speed up things. Downloading assets is a small part of the overall experience of the user with my site. Under those conditions, I would rather optimize for code simplicity and my time rather than asset size. I would rather use a one liner to add all locales than add 20~ more lines to my application.js. If size ever becomes a problem, then I optimize. Just a trade off :)

**Comment by sshaw** [comment]
Yes, a way to include all locales!

The use case is you have an application and the users select their locale. If moments supports it great, if not then a fallback is used.

**Comment by sshaw** [comment]
Or, you import a locale from 3rd party service.  If moments supports it great, if not then a fallback is used.

**Pull request closed without merging**
