### PR TITLE
Update momentjs to 2.24.0.

### PR DESCRIPTION
**Pull request by dimameshcharakou**

### CODE REVIEW

**Comment by liorbrauer** [comment]
@zhublik thanks for submitting the PR, do you have any idea if this gem is still maintained? any chance somebody could merge it?

**Comment by zhublik** [comment]
@liorbrauer unfortunately, I have no idea.

**Comment by derekprior** [comment]
See: https://github.com/derekprior/momentjs-rails/issues/58#issuecomment-545617219

**Comment by derekprior** [comment]
Superceded by 2.29.1

**Pull request closed without merging**
